version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'daily'
      time: '03:03'
      timezone: 'Europe/Oslo'
    groups:
      angular:
        patterns:
          - '@angular/*'
      angular-eslint:
        patterns:
          - 'angular-eslint'
          - '@angular-eslint/*'
      designsystemet:
        patterns:
          - '@digdir/designsystemet*'
      storybook:
        patterns:
          - '@storybook/*'
      react:
        patterns:
          - '@types/react'
          - '@types/react-dom'
          - 'react'
          - 'react-dom'
      nx:
        patterns:
          - '@nx/*'
    open-pull-requests-limit: 5
